drop table TESTDB.RENT_BOOK;
drop SCHEMA TESTDB;
create SCHEMA TESTDB AUTHORIZATION SA;

create TABLE TESTDB.RENT_BOOK (
  ID  IDENTITY NOT NULL PRIMARY KEY,
  BOOK_ID INTEGER NOT NULL,
  CLIENT_ID INTEGER  NOT NULL,
  RENT_PRICE REAL NOT NULL,
  INIT_DATE DATE NOT NULL,
  END_DATE DATE,
  RETURNED BOOLEAN  DEFAULT FALSE
);
